# configs/stage2_config.yaml

# 数据配置 (通常与阶段一相同)
data:
  video_path: "data/videos/1392e8264d9904bfffe142421b784cbd.mp4"
  level_json_path: "resources/level/hard_15-01-obt-hard-level_hard_15-01.json"
  sequence_length: 5
  channels: 3
  height: 256
  width: 256
  num_workers: 4
  use_mock_data: false
  mock_num_samples: 100

# 模型配置
model:
  generator:
    in_channels: 3
    out_channels: 3
    epsilon: 0.03 # 像素级攻击的扰动上限
    num_bottlenecks: 4
    base_channels: 32
  discriminator:
    type: "patchgan"
    in_channels: 3
    base_channels: 64
  atn:
    # 1. 指向真实的权重文件
    model_path: "models/full_atn/iris_transformers_ac_5_ce_4bn_20f_best.pth"
    
    # 2. (新增) IrisBabelModel 初始化所需的参数
    memory_length: 1024
    num_mid_dim: 512
    num_actions: 5
    num_targets: 20
    # (新增) ATN 模型输入形状和结构参数
    atn_in_channels: 3
    atn_sequence_length: 5
    atn_height: 256
    atn_width: 256
    atn_num_heads: 8
    
    # 3. (新增) 合成决策图所需的尺寸信息
    # 你的数据尺寸是 256x256，但决策图可能是在一个更小的特征图上产生的。
    # 你需要和开发者确认决策坐标(x,y)对应的特征图尺寸。这里先假设是 81x81。
    decision_map_height: 81
    decision_map_width: 81

# 训练配置
training:
  train_stage: 2
  batch_size: 2 # 从一个较小的值开始，以防显存溢出
  num_epochs: 1
  lr_g: 0.0005
  lr_d: 0.0005
  b1: 0.5
  b2: 0.999
  seed: 42
  device: "cuda"
  
  # 4. (关键修改) 禁用阶段一权重的加载
  generator_weights_path: null
  discriminator_weights_path: null
  resume_checkpoint: null
  
  eval_interval: 1
  save_interval: 1
  dynamic_gan_balance:
    enabled: true
    strategy: "loss_ratio_freq_adjust"
    freq_adjust_interval: 100
    initial_D_freq: 1
    initial_G_freq: 1
    D_dominant_threshold: 2.0
    G_dominant_threshold: 0.5
    lr_adjust_factor: 0.9
    min_lr: 1e-6
    max_lr: 1e-3
    loss_history_window: 50

# 损失配置
losses:
  gan_type: "lsgan"
  decision_loss_type: "mse"
  attention_loss_type: "topk" # 或 "kl_div"
  decision_loss_weight: 500.0 # 启用决策损失
  attention_loss_weight: 1.0 # 启用注意力损失
  topk_k: 10
  gan_loss_weight: 1.0

# 正则化配置 (从 Stage 1 复制)
regularization:
  lambda_l_inf: 1.0
  lambda_l2: 0.0
  lambda_tv: 0.0
  lambda_l2_penalty: 0.001

# 掩码配置 (如果你的 ATN 有区域掩码) (从 Stage 1 复制)
mask:
  use_region_mask: False
  # decision_mask_path: "resources/masks/decision_mask.png"
  # attention_mask_path: "resources/masks/attention_mask.npy"

# 添加 evaluation 配置
evaluation:
  num_eval_samples: 32 # 评估时使用的样本数量/批次大小
  eval_interval: 50 # 每隔多少个 epoch 进行一次评估
  success_threshold: 0.1
  success_criterion: "mse_diff_threshold"

# 日志配置
logging:
  log_dir: "runs/stage2_train" # 或者保留 default_train
  log_interval: 10 # 每隔 10 步记录一次损失
  vis_interval: 100 # 每隔 100 步可视化一次样本 (可以减小间隔以便调试)
  num_vis_samples: 4
  sequence_step_to_vis: 0
  num_vis_heads: 1 # 添加可视化注意力头数量的配置