# configs/stage2_config.yaml

# 数据配置 (通常与阶段一相同)
data:
  video_path: "data/videos/1392e8264d9904bfffe142421b784cbd.mp4"
  level_json_path: "resources/level/hard_15-01-obt-hard-level_hard_15-01.json"
  sequence_length: 5
  channels: 3
  height: 256
  width: 256
  num_workers: 4

# 模型配置
model:
  generator:
    in_channels: 3
    out_channels: 3
    epsilon: 0.03 # 像素级攻击的扰动上限
    num_bottlenecks: 4
    base_channels: 32
  discriminator:
    type: "patchgan"
    in_channels: 3
    base_channels: 64
  atn:
    # 1. 指向真实的权重文件
    model_path: "models/full_atn/iris_transformers_ac_5_ce_4bn_20f_best.pth"
    
    # 2. (新增) IrisBabelModel 初始化所需的参数
    memory_length: 1024
    num_mid_dim: 512
    num_actions: 5
    num_targets: 20
    
    # 3. (新增) 合成决策图所需的尺寸信息
    # 你的数据尺寸是 256x256，但决策图可能是在一个更小的特征图上产生的。
    # 你需要和开发者确认决策坐标(x,y)对应的特征图尺寸。这里先假设是 81x81。
    decision_map_height: 81
    decision_map_width: 81

# 训练配置
training:
  train_stage: 2
  batch_size: 1 # 从一个较小的值开始，以防显存溢出
  num_epochs: 100
  lr_g: 0.0001
  lr_d: 0.0001
  b1: 0.5
  b2: 0.999
  seed: 42
  device: "cuda"
  
  # 4. (关键修改) 禁用阶段一权重的加载
  generator_weights_path: null
  discriminator_weights_path: null
  resume_checkpoint: null
  
  eval_interval: 5
  dynamic_gan_balance:
    enabled: true
    # ... (其他动态平衡参数可以沿用 stage1 的)

# 损失配置
losses:
  gan_type: "lsgan"
  decision_loss_type: "mse"
  attention_loss_type: "kl_div" # 或 "topk"
  decision_loss_weight: 1.0 # 启用决策损失
  attention_loss_weight: 1.0 # 启用注意力损失
  topk_k: 10
  gan_loss_weight: 1.0

# ... (其他配置，如 logging, regularization，可以暂时沿用 stage1 的)